config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'

  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'}

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_out", to: "devise/sessions#destroy"
    get "sign_up", to: "devise/registrations#new"
    get "forgot_password", to: "devise/passwords#new"
  end
  
  resources :resumes do
    member do
      get 'download'
      delete 'delete_attachment'
      get 'choose_your_template'
      get 'share'
      get 'choose_template_to_be_downloaded'
      get 'show'
    end
    collection do
      get 'choose_templates'
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #resources :sessions, only: [:create]
  
  root "home#index"
end

app/views/pdf/_advance_template.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>W3.CSS Template</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
    html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
    </style>
  </head>
<body class="w3-light-grey">

  <!-- Page Container -->
  <div class="w3-content w3-margin-top" style="max-width:1400px;">

    <!-- The Grid -->
    <div class="w3-row-padding">
    
      <!-- Left Column -->
      <div class="w3-third">
      
        <div class="w3-white w3-text-grey w3-card-4">
          <div class="w3-display-container">
            <% if @resume.avtar.present? %>
              <div class='center'><%= image_tag @resume.avtar,:width=>"445", :height=>"320" %></div>
            <% end %>
          </div>

          <div class="w3-container">
            <h2 class="w3-text-grey w3-padding-16"><i class="bi bi-person fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i><%= @resume.name %></h2>
            <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i>Software Developer</p>
            <hr>
            <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>About Me</b></p>
            <div class="w3-container">
              <p><%= @resume.general_info %></p>
            </div>
            <hr>


            <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Basic Information</b></p>
            <div class="w3-container">
              <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i>Software Developer</p>
              <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.email %></p>
              <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.phone_number %></p>
              <p><i class="bi bi-calendar green-color fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.birthdate %></p>
              <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.address %></p>
              <p><i class="bi bi-globe fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.country %></p>
              <p><i class="fa fa-male fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.gender %></p>
              <p><i class="fa fa-music fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.interests %></p>
              <p><i class="fa fa-website fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.website %></p>
            </div>
            <hr>

            <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Skills</b></p>
            <% if @resume.skills.present? %>
              <% @resume.skills.each do |skill| %>
                <p><%= skill.title %></p>
                <div class="w3-light-grey w3-round-xlarge w3-small">
                  <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:<%= skill.percent %>%;"><%= skill.percent %></div>
                </div>
              <% end %>
            <% end %>
            <hr>


            <p class="w3-large w3-text-theme"><b><i class="fa fa-globe fa-fw w3-margin-right w3-text-teal"></i>Languages</b></p>
            <% if @resume.languages.present? %>
              <% @resume.languages.each do |language| %>
                <p><%= language.name %></p>
                <div class="w3-light-grey w3-round-xlarge">
                  <div class="w3-round-xlarge w3-teal" ></div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div><br>
      </div>

      <!-- End Left Column -->

      <!-- Right Column -->
      <div class="w3-twothird">
      
        <div class="w3-container w3-card w3-white w3-margin-bottom">
          <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Work Experience</h2>
          <% if @resume.jobs.present? %>
            <% @resume.jobs.each do |job| %>
              <div class="w3-container">
                <h4 class="w3-opacity"><b><%= job.firm %></b></h4>
                <h5 class="w3-text-teal"><b><%= job.position %></b></h5>
                <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i><%= "#{job.date_from&.strftime("%B %Y")} - #{job.date_to&.strftime("%B %Y")}" %></h6>
                <p><%= job.description %></p>
                <hr>
              </div>
            <% end %>
          <% end %>
        </div>
          

        <div class="w3-container w3-card w3-white">
          <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Education</h2>
            <% if @resume.educations.present? %>
              <% @resume.educations.each do |education| %>
                <div class="w3-container">
                  <h4><span class="w3-opacity"><b><%= education.level %> - <%= education.course %></b></span></h4>
                  <h5 class="w3-text-teal"><b><%= education.place %></b></h5>
                  <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i><%= "#{education.date_from&.strftime("%B %Y")} - #{education.date_to&.strftime("%B %Y")}" %></h6>
                  <p><%= education.description %></p>
                  <hr>
                </div>
              <% end %>
            <% end %>
        </div>

        <div class="w3-container w3-card w3-white w3-margin-top">
          <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Projects</h2>
            <% if @resume.projects.present? %>
              <% @resume.projects.each do |project| %>
                <div class="w3-container">
                  <h4 class="w3-opacity"><b><%= project.client %></b></h4>
                  <h5 class="w3-text-teal"><%= project.technologies %></h5>
                  <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i><%= "#{project.date_from&.strftime("%B %Y")} - #{project.date_to&.strftime("%B %Y")}" %></h6>
                  <p><%= project.description %></p>
                  <hr>
                </div>
              <% end %>
            <% end %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pdf/_advance_template.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <title>W3.CSS Template</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
    html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
    </style>
  </head>
<body class="w3-light-grey">

<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
  
    <!-- Left Column -->
    <div class="w3-third">
    
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container">
          <% if @resume.avtar.present? %>
            <div class='center'><%= image_tag @resume.avtar,:width=>"445", :height=>"320" %></div>
          <% end %>
        </div>

        <div class="w3-container">
          <h2 class="w3-text-grey w3-padding-16"><i class="bi bi-person fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i><%= @resume.name %></h2>
          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i>Software Developer</p>
          <hr>
          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>About Me</b></p>
          <div class="w3-container">
            <p><%= @resume.general_info %></p>
          </div>
          <hr>


          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Basic Information</b></p>
          <div class="w3-container">
            <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i>Software Developer</p>
            <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.email %></p>
            <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.phone_number %></p>
            <p><i class="bi bi-calendar green-color fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.birthdate %></p>
            <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.address %></p>
            <p><i class="bi bi-globe fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.country %></p>
            <p><i class="fa fa-male fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.gender %></p>
            <p><i class="fa fa-music fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.interests %></p>
            <p><i class="fa fa-website fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.website %></p>
          </div>
          <hr>

          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Skills</b></p>
          <% if @resume.skills.present? %>
            <% @resume.skills.each do |skill| %>
              <p><%= skill.title %></p>
              <div class="w3-light-grey w3-round-xlarge w3-small">
                <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:<%= skill.percent %>%;"><%= skill.percent %></div>
              </div>
            <% end %>
          <% end %>
          <hr>


          <p class="w3-large w3-text-theme"><b><i class="fa fa-globe fa-fw w3-margin-right w3-text-teal"></i>Languages</b></p>
          <% if @resume.languages.present? %>
            <% @resume.languages.each do |language| %>
              <p><%= language.name %></p>
              <div class="w3-light-grey w3-round-xlarge">
                <div class="w3-round-xlarge w3-teal" ></div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div><br>
    </div>

    <!-- End Left Column -->

    <!-- Right Column -->
    <div class="w3-twothird">
    
      <div class="w3-container w3-card w3-white w3-margin-bottom">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Work Experience</h2>
        <% if @resume.jobs.present? %>
          <% @resume.jobs.each do |job| %>
            <div class="w3-container">
              <h4 class="w3-opacity"><b><%= job.firm %></b></h4>
              <h5 class="w3-text-teal"><b><%= job.position %></b></h5>
              <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i><%= "#{job.date_from&.strftime("%B %Y")} - #{job.date_to&.strftime("%B %Y")}" %></h6>
              <p><%= job.description %></p>
              <hr>
            </div>
          <% end %>
        <% end %>
      </div>
        

      <div class="w3-container w3-card w3-white">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Education</h2>
          <% if @resume.educations.present? %>
            <% @resume.educations.each do |education| %>
              <div class="w3-container">
                <h4><span class="w3-opacity"><b><%= education.level %> - <%= education.course %></b></span></h4>
                <h5 class="w3-text-teal"><b><%= education.place %></b></h5>
                <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i><%= "#{education.date_from&.strftime("%B %Y")} - #{education.date_to&.strftime("%B %Y")}" %></h6>
                <p><%= education.description %></p>
                <hr>
              </div>
            <% end %>
          <% end %>
      </div>

      <div class="w3-container w3-card w3-white w3-margin-top">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Projects</h2>
          <% if @resume.projects.present? %>
            <% @resume.projects.each do |project| %>
              <div class="w3-container">
                <h4 class="w3-opacity"><b><%= project.client %></b></h4>
                <h5 class="w3-text-teal"><%= project.technologies %></h5>
                <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i><%= "#{project.date_from&.strftime("%B %Y")} - #{project.date_to&.strftime("%B %Y")}" %></h6>
                <p><%= project.description %></p>
                <hr>
              </div>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>

            


<!-- Footer. This section contains an ad for W3Schools Spaces. You can leave it to support us. -->
<footer class="w3-container w3-teal w3-center w3-margin-top">
  <p>Find me on social media.</p>
  <i class="fa fa-facebook-official w3-hover-opacity"></i>
  <i class="fa fa-instagram w3-hover-opacity"></i>
  <i class="fa fa-snapchat w3-hover-opacity"></i>
  <i class="fa fa-pinterest-p w3-hover-opacity"></i>
  <i class="fa fa-twitter w3-hover-opacity"></i>
  <i class="fa fa-linkedin w3-hover-opacity"></i>
 <p class="w3-small">Share Your Resume</p>
  <%= social_share_button_tag('Share to Facebook', :url => share_resume_path(@resume), desc: @resume.name) %>
  <%= link_to "Share Now", share_resume_path(@resume), class: "w3-button w3-round-xxlarge w3-small w3-light-grey w3-margin-bottom" %>
 </footer>

</body>
</html>

app/views/pdf/_intermediate_template.html.erb
<div class="container card">
      <div class="row">
        <div class="col-12 col-md-4 col-md-offset-2">
          <h3 class="worker-name"> <%= @resume.name %></h3>
          <h5 class="worker-info"> <%= @resume.email %></h5>
          <p class="worker-info"><%= @resume.general_info %></p>
        </div>
        <div class="col-12 col-md-5"></div>
        <div class="col-12 col-md-3">
          <% if @resume.avtar.present? %>
            <div class='pull-right'>
              <%= image_tag @resume.avtar,:width=>"150" %>
            </div>
          <% end %>
        </div>
      </div>
      <hr>

      <div class="row">
        <div class="col-md-5 col-md-offset-2">
          <% if @resume.projects.any? %>
            <h4>Project Experience</h4>
            <% @resume.projects.each do |project| %>
              <div class="project-sections"></div>
              <div class="project-date project-fields">
                <%= project.date_from&.strftime('%B %Y') %> -
                <%= project.date_to&.strftime('%B %Y') %>
                <span style="display: block; color: #2E2F30"><strong>Client</strong>: <%= project.client %></span>
              </div>
              <div class="project-fields">
                <strong>Project description</strong>: <%= project.description %>
              </div>
              <div class="project-fields">
                <strong>Used technologies</strong>: <%= project.technologies %>
              </div>
              <div class="project-fields">
                <strong>Role in project</strong>: <%= project.role %>
              </div>
              <div class="project-fields">
                <strong>Level</strong>: <%= project.level %>
              </div>
              <div class="project-fields">
                <strong>Team Size</strong>: <%= project.team_size %>
              </div>
            <% end %>
          <% end %>
        </div>

        <div class="col-md-5 col-md-offset-2">
          <% if @resume.jobs.any? %>
            <h4>Job Experience</h4>
            <% @resume.jobs.each do |job| %>
              <div class="project-sections-jobs"></div>
              <div class="project-date job-fields">
                <%= job.date_from&.strftime("%d.%m.%y") %> -
                <%= job.date_to&.strftime("%d.%m.%y") %>
                <span style="display: block; color: #2E2F30"><strong>Company</strong>: <%= job.firm %></span>
              </div>
              <div class="project-fields">
                <strong>Position</strong>: <%= job.position %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
        <hr>
        <div class="row">
          <div class="col-md-5 col-md-offset-2">
            <% if @resume.skills.any? %>
              <h4>Skills & Competences</h4>
              <%= section = '' %>
              <% @resume.skills.order('section').order('percent DESC').each do |skill| %>
                <% if section != skill.section %>
                  <h5><%= section = skill.section %></h5>
                <% end %>
                <div class="skillbar clearfix " data-percent="<%= skill.percent %>%">
                  <div class="skill-title"><strong><span class="skill-title">Skills</span>:</strong><%= skill.title %></div>
                  <div class="skill-bar-percent"><%= skill.percent %>%</div>
                </div> <!-- End Skill Bar -->
              <% end %>
            <% end %>
          </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-5 col-md-offset-2">
          <% if @resume.educations.any? %>
            <h4>Education</h4>
            <% @resume.educations.each do |education| %>
              <div class="project-sections-education"></div>
              <div class="project-date project-fields">
                <%= education.date_from&.strftime('%B %Y') %> -
                <%= education.date_to&.strftime('%B %Y') %>
              </div>
              <div>
                <span class="project-fields"><strong>College Name</strong>:<%= education.place %></span>
              </div>
              <% if education.level.empty? %>
                <div class="project-fields">
                  <strong>Description</strong>: <%= education.description %>
                </div>
              <% else %>
                <div class="project-fields">
                  <strong>Level</strong>: <%= education.level %>
                </div>
                <div class="project-fields">
                  <strong>Description</strong>: <%= education.description %>
                </div>
               <% end %>
            <% end %>
          <% end %>
        </div>

        <div class="col-md-5 col-md-offset-2">
          <% if @resume.languages.any? %>
            <h4>Languages</h4>
            <% @resume.languages.each do |language| %>
              <p><span><%= language.name%></span>
            <% end %>
          <% end %>
        </div>
      </div>
      <hr>
    <div class="row">
      <div class="col-md-5 col-md-offset-2">
        <h4>Interests</h4>
        <span><%= @resume.interests %></span>
      </div>
    </div>
  </div>

app/views/pdf/_intermediate_template.pdf.erb
<div class="page-content">
  <div>
    <div class="profile-page">
      <div class="wrapper">
        <div class="page-header page-header-small" filter-color="green">
          <div class="page-header-image" data-parallax="true" style="background-image: url('images/cc-bg-1.jpg')"></div>
          <div class="container">
            <div class="content-center">
              <div class="row">
                <div class="col-12 col-sm-6">
                  <% if @resume.avtar.present? %>
                    <%= image_tag @resume.avtar %>
                  <% end %>
                </div>
                <div class="col-12">
                  <div class="pull-right"><h2><%= @resume.name %></h2></div>
                  <p class="category text-white"><Web Developer, Graphic Designer, Photographer></p>
                    
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
      
<div class="section" id="about">
  <div class="container">
    <div class="card" data-aos="fade-up" data-aos-offset="10">
      <div class="row">
        <div class="col-lg-6 col-md-12">
          <div class="card-body">
            <div class="h4 mt-0 title">About</div>
            <p>Hello! I am <%= @resume.name %></p>
            <p><%= @resume.general_info %></p>
          </div>
        </div>
        <div class="col-lg-6 col-md-12">
          <div class="card-body">
            <div class="h4 mt-0 title">Basic Information</div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Email:</strong></div>
              <div class="col-sm-8"><%= @resume.email %></div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Gender:</strong></div>
              <div class="col-sm-8"><%= @resume.gender %></div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Birthdate:</strong></div>
              <div class="col-sm-8"><%= @resume.birthdate %></div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Contact:</strong></div>
              <div class="col-sm-8"><%= @resume.phone_number %></div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Website:</strong></div>
              <div class="col-sm-8"><%= @resume.website %></div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Address:</strong></div>
              <div class="col-sm-8"><%= @resume.address %></div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Country:</strong></div>
              <div class="col-sm-8"><%= @resume.country %></div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Language:</strong></div>
              <div class="col-sm-8"><%= @resume.languages.pluck(:name).join(", ") %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container cc-education">
    <div class="h4 text-center mb-4 title">Education</div>
    <% if @resume.educations.present? %>
      <% @resume.educations.each do |education| %>
        <div class="card">
          <div class="row">
            <div class="col-md-3 bg-primary" data-aos="fade-right" data-aos-offset="50" data-aos-duration="500">
              <div class="card-body cc-education-header">
                <p><%= "#{education.date_from&.strftime("%B %Y")} - #{education.date_to&.strftime("%B %Y")}" %></p>
                <div class="h5"><%= education.level %></div>
              </div>
            </div>

            <div class="col-md-9" data-aos="fade-left" data-aos-offset="50" data-aos-duration="500">
              <div class="card-body">
                <div class="h5"><%= education.course %></div>
                <p class="category"><%= education.place %></p>
                <p><%= education.description %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>


<div class="section" id="skill">
  <div class="container">
    <div class="h4 text-center mb-4 title">Professional Skills</div>
    <div class="card" data-aos="fade-up" data-aos-anchor-placement="top-bottom">
      <div class="card-body">
        <div class="row">
          <% if @resume.skills.present? %>
            <% @resume.skills.each do |skill| %>
              <div class="col-md-6">
                <div class="progress-container progress-primary"><span class="progress-badge"><%= skill.title %></span>
                  <div class="progress">
                    <div class="progress-bar progress-bar-primary" data-aos="progress-full" data-aos-offset="10" data-aos-duration="2000" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= skill.percent %>%;"></div><span class="progress-value"><%= skill.percent %></span>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="section" id="experience">
  <div class="container cc-experience">
    <div class="h4 text-center mb-4 title">Project Experience</div>
    <% if @resume.projects.present? %>
      <% @resume.projects.each do |project| %>
        <div class="card">
          <div class="row">
            <div class="col-md-3 bg-primary" data-aos="fade-right" data-aos-offset="50" data-aos-duration="500">
              <div class="card-body cc-experience-header">
                <p><%= "#{project.date_from&.strftime("%B %Y")} - #{project.date_to&.strftime("%B %Y")}" %></p>
                <div class="h5"><%= project.client %></div>
              </div>
            </div>
            <div class="col-md-9" data-aos="fade-left" data-aos-offset="50" data-aos-duration="500">
              <div class="card-body">
                <div class="h5"><%= project.technologies %></div>
                <p><%= project.description %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>


<div class="section" id="experience">
  <div class="container cc-experience">
    <div class="h4 text-center mb-4 title">Work Experience</div>
    <% if @resume.jobs.present? %>
      <% @resume.jobs.each do |job| %>
        <div class="card">
          <div class="row">
            <div class="col-md-3 bg-primary" data-aos="fade-right" data-aos-offset="50" data-aos-duration="500">
              <div class="card-body cc-experience-header">
                <p><%= "#{job.date_from&.strftime("%B %Y")} - #{job.date_to&.strftime("%B %Y")}" %></p>
                <div class="h5"><%= job.firm %></div>
              </div>
            </div>
            <div class="col-md-9" data-aos="fade-left" data-aos-offset="50" data-aos-duration="500">
              <div class="card-body">
                <div class="h5"><%= job.position %></div>
                <p><%= job.place %></p>
                <p><%= job.description %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>



    
  
  
    <script src="js/core/jquery.3.2.1.min.js?ver=1.1.0"></script>
    <script src="js/core/popper.min.js?ver=1.1.0"></script>
    <script src="js/core/bootstrap.min.js?ver=1.1.0"></script>
    <script src="js/now-ui-kit.js?ver=1.1.0"></script>
    <script src="js/aos.js?ver=1.1.0"></script>
    <script src="scripts/main.js?ver=1.1.0"></script>
</body>

app/views/pdf/download_templates.html.erb
<% if @resume_type == "Normal" %>
  <%= render "pdf/normal_template" %>
<% elsif @resume_type == "Intermediate" %>
  <%= render "pdf/intermediate_template" %>
<% elsif @resume_type == "Advanced" %>
  <%= render "pdf/advance_template" %>
<% elsif @resume_type == "Pro" %>
  <%= render "pdf/pro_template" %>
<% end %>

app/views/pdf/download_templates.pdf.erb
<% if @resume_type == "Normal" %>
  <%= render "pdf/normal_template" %>
<% elsif @resume_type == "Intermediate" %>
  <%= render "pdf/intermediate_template" %>
<% elsif @resume_type == "Advanced" %>
  <%= render "pdf/advance_template" %>
<% elsif @resume_type == "Pro" %>
  <%= render "pdf/pro_template" %>
<% end %>