config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'

  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'}

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_out", to: "devise/sessions#destroy"
    get "sign_up", to: "devise/registrations#new"
    get "forgot_password", to: "devise/passwords#new"
  end
  
  resources :resumes do
    member do
      get 'download'
      delete 'delete_attachment'
      get 'choose_your_template'
      get 'share'
      get 'choose_template_to_be_downloaded'
      get 'show'
    end
    collection do
      get 'choose_templates'
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #resources :sessions, only: [:create]
  
  root "home#index"
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user

  include ResumeAttachment

  has_many :skills, dependent: :destroy, :foreign_key => "resume_id"
  accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true
  
  has_many :languages, dependent: :destroy, :foreign_key => "resume_id"
  accepts_nested_attributes_for :languages, reject_if: :all_blank, allow_destroy: true
  
  has_many :projects, dependent: :destroy, :foreign_key => "resume_id"
  accepts_nested_attributes_for :projects, reject_if: :all_blank, allow_destroy: true
  
  has_many :educations, dependent: :destroy, :foreign_key => "resume_id"
  accepts_nested_attributes_for :educations, reject_if: :all_blank, allow_destroy: true
  
  has_many :awards, dependent: :destroy, :foreign_key => "resume_id"
  
  has_many :jobs, dependent: :destroy, :foreign_key => "resume_id"
  accepts_nested_attributes_for :jobs, reject_if: :all_blank, allow_destroy: true
  
  has_one :share_cv

  enum gender: ["MALE", "FEMALE", "OTHER"]

  validates :name, presence: true,
            length: {minimum: 3}

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :general_info, presence: true, length: {minimum: 10}
  validates :phone_number, presence: true
  validates :user_id, presence: true
  validates :country, presence: true
  validates :address, presence: true
  validates :general_info, presence: true

  def to_param
    [id, name.parameterize].join('-')
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController

  def index
    @nav_header_menus = [
                          {:href => root_path, :label => "Home", :arrowBack => true}
                        ]
    @resumes = current_user.resumes
  end

  def show
    @nav_header_menus = [
                          {:href => choose_your_template_resume_path, :label => "My Resumes", :arrowBack => true}
                        ]
    
    @resume = current_user.resumes.find(params[:id])
    @template_type = params[:type]
  end

  def download
    @resume_type = params[:resume_type]
    @resume = current_user.resumes.find(params[:id])
    respond_to do |format|
      format.pdf do
        render :pdf => "#{@resume.name}",
               :layout => "pdf",
               :template => "pdf/download_templates",
               :margin => { :top => 10, :bottom => 10, :left => 10, :right => 10},
               :viewport_size => '1280x1024',
               disposition: 'attachment'
      end
    end
  end

  def new
    common_desktop_nav_header
    @resume_type = params[:type]
    if current_user.present?
      @step = 1
      @resume = current_user.resumes.new
      @resume.skills.build unless @resume.skills.present?
    else
      redirect_to root_path, notice: "Please login first"
    end
  end

  def edit
    @step = params[:step]
    @resume = current_user.resumes.find(params[:id])
  end

  def create
    @step = params[:step]
    @resume = current_user.resumes.new(resume_params)

    if @resume.save!
      redirect_to edit_resume_path(@resume, step: 2 )
    else
      render 'new'
    end
  end

  def update
    @resume = current_user.resumes.find(params[:id])

    if @resume.update(resume_params)
      step = params[:proceed_next] ? params[:step].to_i+1 : params[:step].to_i
      url = params[:proceed_next] ? edit_resume_path(@resume, step:  step) : resume_path(@resume)
      redirect_to url 
    else
      render 'edit'
    end
  end

  def delete_attachment
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    redirect_to request.referer
  end

  def destroy
    @resume = current_user.resumes.find(params[:id])
    @resume.destroy
    redirect_to resumes_path
  end

  

  def choose_your_template
    common_desktop_nav_header
    @resume = current_user.resumes.find(params[:id])
  end

  def choose_template_to_be_downloaded
    common_desktop_nav_header
    @resume = current_user.resumes.find(params[:id])
  end

  def share
    resume = current_user.resumes.find(params[:id])
    @share_cv = resume.share_cv ? resume.share_cv : ShareCv.new
    
    @share_cv.theme = "simple" if @share_cv && @share_cv.theme.nil?
    if Rails.env.production?
      bitly = Bitly.new("sreeharikmarar", "R_4f00b6fbbd62eaa6c81a48b9b0d7dab4")
      b = bitly.shorten("http://#{request.host_with_port}/profile/"+current_user.id.to_s)
      @url =  b.short_url
    else
      @url =  "http://#{request.host_with_port}/profile/"+current_user.id.to_s
    end
      
    respond_to do |format|
      format.html { }
      format.js { }
    end
  end

  def choose_templates
    @nav_header_menus = [
                          {:href => root_path, :label => "Home", :arrowBack => true},
                        ]
  end

  private
  def resume_params
    params.require(:resume).permit(:name, :avtar, :general_info, :phone_number, :interests, :user_id, :address, :country, :birthdate, :gender, :website, :email,
                                   skills_attributes: [:id, :section, :title, :percent, :_destroy],
                                   languages_attributes: [:id, :name, :_destroy],
                                   projects_attributes:[:id, :date_from, :date_to, :client, :description, :technologies, :role, :level, :team_size, :_destroy],
                                   educations_attributes:[:id, :date_from, :date_to, :level, :description, :place, :course, :_destroy],
                                   jobs_attributes: [:id, :date_from, :date_to, :firm, :description, :position, :place, :_destroy])
  end
end

app/views/resumes/_advance.html.erb
<div class="page-content">
  <div>
    <div class="profile-page">
      <div class="wrapper">
        <div class="page-header page-header-small" filter-color="green">
          <div class="page-header-image" data-parallax="true" style="background-image: url('images/cc-bg-1.jpg')"></div>
          <div class="container">
            <div class="content-center">
              <div class="cc-profile-image">
                <% if @resume.avtar.present? %>
                  <div class='center'><%= image_tag @resume.avtar,:width=>"200", :height=>"200" %></div>
                <% end %>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="pull-right"><h2><%= @resume.name %></h2></div>
                  <p class="category text-white"><Web Developer, Graphic Designer, Photographer></p>
                    
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
      
<div class="section" id="about">
  <div class="container">
    <div class="card" data-aos="fade-up" data-aos-offset="10">
      <div class="row">
        <div class="col-lg-6 col-md-12">
          <div class="card-body">
            <div class="h4 mt-0 title">About</div>
            <p>Hello! I am <%= @resume.name %></p>
            <p><%= @resume.general_info %></p>
          </div>
        </div>
        <div class="col-lg-6 col-md-12">
          <div class="card-body">
            <div class="h4 mt-0 title">Basic Information</div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Email:</strong></div>
              <div class="col-sm-8"><%= @resume.email %></div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Phone:</strong></div>
              <div class="col-sm-8"><%= @resume.phone_number %></div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Address:</strong></div>
              <div class="col-sm-8"><%= @resume.address %></div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Language:</strong></div>
              <div class="col-sm-8"><%= @resume.languages.pluck(:name).join(", ") %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container cc-education">
    <div class="h4 text-center mb-4 title">Education</div>
    <% if @resume.educations.present? %>
      <% @resume.educations.each do |education| %>
        <div class="card">
          <div class="row">
            <div class="col-md-3 bg-primary" data-aos="fade-right" data-aos-offset="50" data-aos-duration="500">
              <div class="card-body cc-education-header">
                <p><%= "#{education.date_from&.strftime("%B %Y")} - #{education.date_to&.strftime("%B %Y")}" %></p>
                <div class="h5"><%= education.level %></div>
              </div>
            </div>

            <div class="col-md-9" data-aos="fade-left" data-aos-offset="50" data-aos-duration="500">
              <div class="card-body">
                <div class="h5"><%= education.course %></div>
                <p class="category"><%= education.place %></p>
                <p><%= education.description %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>


<div class="section" id="skill">
  <div class="container">
    <div class="h4 text-center mb-4 title">Professional Skills</div>
    <div class="card" data-aos="fade-up" data-aos-anchor-placement="top-bottom">
      <div class="card-body">
        <div class="row">
          <% if @resume.skills.present? %>
            <% @resume.skills.each do |skill| %>
              <div class="col-md-6">
                <div class="progress-container progress-primary"><span class="progress-badge"><%= skill.title %></span>
                  <div class="progress">
                    <div class="progress-bar progress-bar-primary" data-aos="progress-full" data-aos-offset="10" data-aos-duration="2000" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= skill.percent %>%;"></div><span class="progress-value"><%= skill.percent %></span>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="section" id="experience">
  <div class="container cc-experience">
    <div class="h4 text-center mb-4 title">Project Experience</div>
    <% if @resume.projects.present? %>
      <% @resume.projects.each do |project| %>
        <div class="card">
          <div class="row">
            <div class="col-md-3 bg-primary" data-aos="fade-right" data-aos-offset="50" data-aos-duration="500">
              <div class="card-body cc-experience-header">
                <p><%= "#{project.date_from&.strftime("%B %Y")} - #{project.date_to&.strftime("%B %Y")}" %></p>
                <div class="h5"><%= project.client %></div>
              </div>
            </div>
            <div class="col-md-9" data-aos="fade-left" data-aos-offset="50" data-aos-duration="500">
              <div class="card-body">
                <div class="h5"><%= project.technologies %></div>
                <p><%= project.description %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>


<div class="section" id="experience">
  <div class="container cc-experience">
    <div class="h4 text-center mb-4 title">Work Experience</div>
    <% if @resume.jobs.present? %>
      <% @resume.jobs.each do |job| %>
        <div class="card">
          <div class="row">
            <div class="col-md-3 bg-primary" data-aos="fade-right" data-aos-offset="50" data-aos-duration="500">
              <div class="card-body cc-experience-header">
                <p><%= "#{job.date_from&.strftime("%B %Y")} - #{job.date_to&.strftime("%B %Y")}" %></p>
                <div class="h5"><%= job.firm %></div>
              </div>
            </div>
            <div class="col-md-9" data-aos="fade-left" data-aos-offset="50" data-aos-duration="500">
              <div class="card-body">
                <div class="h5"><%= job.position %></div>
                <p><%= job.place %></p>
                <p><%= job.description %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>



    
  
  
    <script src="js/core/jquery.3.2.1.min.js?ver=1.1.0"></script>
    <script src="js/core/popper.min.js?ver=1.1.0"></script>
    <script src="js/core/bootstrap.min.js?ver=1.1.0"></script>
    <script src="js/now-ui-kit.js?ver=1.1.0"></script>
    <script src="js/aos.js?ver=1.1.0"></script>
    <script src="scripts/main.js?ver=1.1.0"></script>
</body>

app/views/resumes/_advance2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>W3.CSS Template</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
    html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
    </style>
  </head>
<body class="w3-light-grey">

<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
  
    <!-- Left Column -->
    <div class="w3-third">
    
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container">
          <% if @resume.avtar.present? %>
            <div class='center'><%= image_tag @resume.avtar,:width=>"445", :height=>"320" %></div>
          <% end %>
        </div>

        <div class="w3-container">
          <h2 class="w3-text-grey w3-padding-16"><i class="bi bi-person fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i><%= @resume.name %></h2>
          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i>Software Developer</p>
          <hr>
          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>About Me</b></p>
          <div class="w3-container">
            <p><%= @resume.general_info %></p>
          </div>
          <hr>


          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Basic Information</b></p>
          <div class="w3-container">
            <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i>Software Developer</p>
            <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.email %></p>
            <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.phone_number %></p>
            <p><i class="bi bi-calendar green-color fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.birthdate %></p>
            <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.address %></p>
            <p><i class="bi bi-globe fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.country %></p>
            <p><i class="fa fa-male fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.gender %></p>
            <p><i class="fa fa-music fa-fw w3-margin-right w3-large w3-text-teal"></i><%= @resume.interests %></p>
          </div>
          <hr>

          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Skills</b></p>
          <% if @resume.skills.present? %>
            <% @resume.skills.each do |skill| %>
              <p><%= skill.title %></p>
              <div class="w3-light-grey w3-round-xlarge w3-small">
                <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:<%= skill.percent %>%;"><%= skill.percent %></div>
              </div>
            <% end %>
          <% end %>
          <hr>


          <p class="w3-large w3-text-theme"><b><i class="fa fa-globe fa-fw w3-margin-right w3-text-teal"></i>Languages</b></p>
          <% if @resume.languages.present? %>
            <% @resume.languages.each do |language| %>
              <p><%= language.name %></p>
              <div class="w3-light-grey w3-round-xlarge">
                <div class="w3-round-xlarge w3-teal" ></div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div><br>
    </div>

    <!-- End Left Column -->

    <!-- Right Column -->
    <div class="w3-twothird">
    
      <div class="w3-container w3-card w3-white w3-margin-bottom">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Work Experience</h2>
        <% if @resume.jobs.present? %>
          <% @resume.jobs.each do |job| %>
            <div class="w3-container">
              <h4 class="w3-opacity"><b><%= job.firm %></b></h4>
              <h5 class="w3-text-teal"><b><%= job.position %></b></h5>
              <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i><%= "#{job.date_from&.strftime("%B %Y")} - #{job.date_to&.strftime("%B %Y")}" %></h6>
              <p><%= job.description %></p>
              <hr>
            </div>
          <% end %>
        <% end %>
      </div>
        

      <div class="w3-container w3-card w3-white">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Education</h2>
          <% if @resume.educations.present? %>
            <% @resume.educations.each do |education| %>
              <div class="w3-container">
                <h4><span class="w3-opacity"><b><%= education.level %> - <%= education.course %></b></span></h4>
                <h5 class="w3-text-teal"><b><%= education.place %></b></h5>
                <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i><%= "#{education.date_from&.strftime("%B %Y")} - #{education.date_to&.strftime("%B %Y")}" %></h6>
                <p><%= education.description %></p>
                <hr>
              </div>
            <% end %>
          <% end %>
      </div>

      <div class="w3-container w3-card w3-white w3-margin-top">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Projects</h2>
          <% if @resume.projects.present? %>
            <% @resume.projects.each do |project| %>
              <div class="w3-container">
                <h4 class="w3-opacity"><b><%= project.client %></b></h4>
                <h5 class="w3-text-teal"><%= project.technologies %></h5>
                <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i><%= "#{project.date_from&.strftime("%B %Y")} - #{project.date_to&.strftime("%B %Y")}" %></h6>
                <p><%= project.description %></p>
                <hr>
              </div>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>

            


<!-- Footer. This section contains an ad for W3Schools Spaces. You can leave it to support us. -->
<footer class="w3-container w3-teal w3-center w3-margin-top">
  <p>Find me on social media.</p>
  <i class="fa fa-facebook-official w3-hover-opacity"></i>
  <i class="fa fa-instagram w3-hover-opacity"></i>
  <i class="fa fa-snapchat w3-hover-opacity"></i>
  <i class="fa fa-pinterest-p w3-hover-opacity"></i>
  <i class="fa fa-twitter w3-hover-opacity"></i>
  <i class="fa fa-linkedin w3-hover-opacity"></i>
 <p class="w3-small">Share Your Resume</p>
 <a class="w3-button w3-round-xxlarge w3-small w3-light-grey w3-margin-bottom" href="#" target="_blank">Share Now</a> <!-- End footer -->
 </footer>

</body>
</html>

app/views/resumes/_fetchAll.html.erb
<div class="row mb-n3 mb-md-n4">
  <div class="col-12 col-md-6 col-lg-4 mb-3 mb-md-4 pb-1">
    <a class="items-box" href="/resumes/choose_templates">
      <div class="item-icon items-add-user wb-rounded">
        <%= image_tag  "icon-create-customer.svg" %>
      </div>
    <a>
  </div>
  <% if @resumes.present?   %>
    <% @resumes.each do |resume| %>
      <%= render 'resumes_show', resume: resume %>
    <% end %>
  <% else %>
    <div class="col-12 col-sm-6 col-md-4 col-10 alert alert-warning">
      <span>
        <%= "no record found" %>
      </span>
    </div>
  <% end %>
</div>

app/views/resumes/_form_step_3.html.erb
<section class="section-details" >
  <div class="container">
    <%= form_for(@resume, :url => (@resume.new_record? ? resumes_path : resume_path(@resume)), :method => (@resume.new_record? ? "POST" : "PUT"), :html => {:multipart => true, :id => 'user-form'}) do |f| %>
      <%= hidden_field_tag "step", @step.to_i %>
      <div class="row">
        <div class="col-12 col-sm-9">
          <div class="items-left wb-rounded">
            <div class="item-header">
              <div class="row mx-n2">
                <div class="col-12">
                  <div class="text-center"><h4>Job Experience</h4></div>
                  <div id="jobs">
                    <% jb =  @resume.jobs.blank? ? @resume.jobs.build : "" %>
                    <%= f.fields_for :jobs do |job| %>
                      <%= render 'jobs_fields', f: job %>
                    <% end %>
                    <div class="text-right">
                      <%= link_to_add_association 'Add more', f, :jobs, partial: 'jobs_fields', class: 'add-buttons pull-right' %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
        <div class="col-12 col-sm-3">
          <div class="items-btns">
            <a class="btn btn-primary" href="<%= edit_resume_path(@resume, step: 2) %>">
              RETURN
              <span class="icon-close-back"></span>
            </a>
            <button class="btn btn-primary" id="saveMedia" name="save" type="submit">
              SAVE
              <span class="icon-next"></span>
            </button>
            <button class="btn btn-primary" name="proceed_next" type="submit">
              <br class="d-none d-md-block">
              </br>
              SAVE AND NEXT
              <span class="icon-next"></span>
            </button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

    

app/views/resumes/_form_step_4.html.erb
<section class="section-details" >
  <div class="container">
    <%= form_for(@resume, :url => (@resume.new_record? ? resumes_path : resume_path(@resume)), :method => (@resume.new_record? ? "POST" : "PUT"), :html => {:multipart => true, :id => 'user-form'}) do |f| %>
      <%= hidden_field_tag "step", @step.to_i %>
      <div class="row">
        <div class="col-12 col-sm-9">
          <div class="items-left wb-rounded">
            <div class="item-header">
              <div class="row mx-n2">
                <div class="col-12">
                  <div class="text-center"><h4>Education</h4></div>
                  <div id="educations">
                    <% edu =  @resume.educations.blank? ? @resume.educations.build : "" %>
                    <%= f.fields_for :educations, edu do |education| %>
                      <%= render 'educations_fields', f:education %>
                    <% end %>

                    <div class="text-right">
                      <%= link_to_add_association 'Add more', f, :educations, partial: 'educations_fields', class: 'add-buttons pull-right' %>
                    </div>
                  </div>
                </div>
              </div>
              <hr>
              <div class="row mx-n2">
                <div class="col-12">
                  <div class="text-center"><h4>Skills</h4></div>
                  <div id="skills">
                    <% skil =  @resume.skills.blank? ? @resume.skills.build : "" %>
                    <%= f.fields_for :skills, skil do |skill| %>
                      <%= render 'skill_fields', f: skill %>
                    <% end %>
                    <div class="text-right">
                      <%= link_to_add_association 'Add skills', f, :skills, partial: 'skill_fields', class: 'add-buttons pull-right' %>
                    </div>
                  </div>
                </div>
              </div>
              <hr>
              <div class="row mx-n2">
                <div class="col-12">
                  <div class="text-center"><h4>Languages</h4></div>
                  <div id="languages">
                    <% lang =  @resume.languages.blank? ? @resume.languages.build : "" %>
                    <%= f.fields_for :languages, lang do |language| %>
                      <%= render 'languages_fields', f: language %>
                    <% end %>
                    <div class="text-right">
                      <%= link_to_add_association 'Add more languages', f, :languages, partial: 'languages_fields', class: 'add-buttons' %>
                    </div>
                  </div>
                </div>
              </div>
              <hr>
            
          
              <div class="row mx-n2">
                <div class="col-12">
                  <div class="text-center"><h4>Upload Image</h4></div>
                  <div id="languages">
                    <%= f.file_field :avtar, :class => "form-control" %>
                    <% if f.object.avtar.present? %>
                      <%= image_tag(f.object.avtar)  %>
                      <%= link_to 'Remove',delete_attachment_resume_path(:id => @resume.avtar.id), method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-12 col-sm-3">
          <div class="items-btns">
            <a class="btn btn-primary" href="<%= edit_resume_path(@resume, step: 3) %>">
              RETURN
              <span class="icon-close-back"></span>
            </a>
            <button class="btn btn-primary" id="saveMedia" name="save" type="submit">
              SAVE
              <span class="icon-next"></span>
            </button>
            <button class="btn btn-primary" type="submit">
              <br class="d-none d-md-block">
              </br>
              SAVE AND NEXT
              <span class="icon-next"></span>
            </button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/resumes/choose_templates.html.erb
<section class="section-box">
  <div class="container">
    <div class="text-center"><h1><strong>Create a Job Winning Resume Now</strong></h1></div>
    <div class="row row-md-17">
      
      
      <div class="col-12 col-sm-6 col-lg-6">
        <a class="items-box" href="<%= new_resume_path(:type => "Normal") %>">
          <div class="item-icon">
            <%= image_tag  "Basic-Template.jpeg" %>
          </div>
          <div class="item-name">
            <%= "BASCIS" %>
          </div>
        </a>
      </div>
      <div class="col-12 col-sm-6 col-lg-6">
        <a class="items-box" href="<%= new_resume_path(:type => "Intermediate") %>">
          <div class="item-icon">
            <%= image_tag  "Choose_template_intermediate.jpeg", :width => "50" %>
          </div>
          <div class="item-name">
            <%= "Intermediate" %>
          </div>
        </a>
      </div>
      <div class="col-12 col-sm-6 col-lg-6 pt-4">
        <a class="items-box" href="<%= new_resume_path(:type => "Advanced") %>">
          <div class="item-icon">
            <%= image_tag  "Choose_template_advance.jpeg" %>
          </div>
          <div class="item-name">
            <%= "Advanced" %>
          </div>
        </a>
      </div>
      <div class="col-12 col-sm-6 col-lg-6 pt-4">
        <a class="items-box" href="<%= new_resume_path(:type => "Pro") %>">
          <div class="item-icon">
            <%= image_tag  "Pro_Template.jpeg" %>
          </div>
          <div class="item-name">
            <%= "Pro" %>
          </div>
        </a>
      </div>
    </div>
  </div>
  <%= render 'home/footer' %>
</section>

app/views/resumes/new.html.erb
<%= render 'form' %>